import { Component, EventEmitter, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { combineLatest } from 'rxjs/observable/combineLatest';
import { ChatsService } from "~/services/chats.service";
import { GetChat } from "~/types";
import { Location } from '@angular/common';

@Component({
  moduleId: module.id,
  template: `
    <!--<app-toolbar>
      <button class="navigation" mat-button (click)="goToChats()">
        <mat-icon aria-label="Icon-button with an arrow back icon">arrow_back</mat-icon>
      </button>
      <div class="title">{{ name }}</div>
    </app-toolbar>
    <div class="container">
      <app-messages-list [items]="messages" [isGroup]="isGroup"
                         appSelectableList="multiple_press" (multiple)="deleteMessages($event)">
        <app-confirm-selection #confirmSelection></app-confirm-selection>
      </app-messages-list>
      <app-new-message (newMessage)="addMessage($event)"></app-new-message>
    </div>-->

    <StackLayout>
      <app-messages-list [items]="messages" [isGroup]="isGroup"
                         appSelectableList="multiple_press" [selectionConfirmed]="selectionConfirmed"
                         (multiple)="deleteMessages($event)">
          <app-confirm-selection #confirmSelection (emitClick)="selectionConfirmed.emit(null)"></app-confirm-selection>
      </app-messages-list>
    
      <app-new-message (newMessage)="addMessage($event)"></app-new-message>
    </StackLayout>
  `,
  styleUrls: ['./chat.component.css'],
})
export class ChatComponent implements OnInit {
  chatId: string;
  messages: GetChat.Messages[];
  name: string;
  isGroup: boolean;
  optimisticUI: boolean;
  selectionConfirmed = new EventEmitter<null>();

  constructor(private route: ActivatedRoute,
              private router: Router,
              private location: Location,
              private chatsService: ChatsService) {
  }

  ngOnInit() {
    combineLatest(this.route.params, this.route.queryParams,
      (params: { id: string }, queryParams: { oui?: boolean }) => ({params, queryParams}))
      .subscribe(({params: {id: chatId}, queryParams: {oui}}) => {
        this.chatId = chatId;

        this.optimisticUI = oui;

        if (this.optimisticUI) {
          // We are using fake IDs generated by the Optimistic UI
          this.chatsService.addChat$.subscribe(({data: {addChat, addGroup}}) => {
            this.chatId = addChat ? addChat.id : addGroup.id;
            console.log(`Switching from the Optimistic UI id ${chatId} to ${this.chatId}`);
            // Rewrite the URL
            this.location.go(`chat/${this.chatId}`);
            // Optimistic UI no more
            this.optimisticUI = false;
          });
        }

        this.chatsService.getChat(chatId, this.optimisticUI).chat$.subscribe(chat => {
          this.messages = chat.messages;
          this.name = chat.name;
          this.isGroup = chat.isGroup;
        });
      });
  }

  goToChats() {
    this.router.navigate(['/chats']);
  }

  addMessage(content: string) {
    console.log('addMessage');
    this.chatsService.addMessage(this.chatId, content).subscribe();
  }

  deleteMessages(messageIds: string[]) {
    //this.chatsService.removeMessages(this.chatId, this.messages, messageIds).subscribe();
  }
}
